# Generated by Django 5.0.6 on 2024-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('pofesion', models.TextField()),
                ('imagen_de_perfil', models.ImageField(upload_to='photos')),
                ('ciudad', models.TextField()),
            ],
        ),
    ]
